# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "hugo-theme-goblog"
license = "MIT"
licenselink = "https://github.com/mengzhuo/hugo-theme-goblog/blob/master/LICENSE"
description = ""
homepage = "http://github.com/mengzhuo/hugo-theme-goblog"
tags = ["blog"]
features = []
min_version = "0.41"

[author]
  name = "Meng Zhuo"
  homepage = "https://mzh.io"

# If porting an existing theme
[original]
  name = "Go blog"
  homepage = "https://blog.golang.org"
  repo = ""
